/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Color;

/**
 * frmDB - ventana de configuración de base de datos
 */
public class frmDB extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmDB.class.getName());

    public frmDB() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        setResizable(false);
        // Cargar ajustes al abrir
        loadSettings();
    // initialize the UI checkbox state from updater settings
    try { CheckBoxAutoUpdater.setSelected(Updater.isAutoUpdateEnabled()); } catch (Exception ignored) { CheckBoxAutoUpdater.setSelected(true); }
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Forms/icon.png")).getImage());
        btnRegresar.setUI(new javax.swing.plaf.basic.BasicButtonUI());
        btnSaveSettings.setUI(new javax.swing.plaf.basic.BasicButtonUI());
        btnTestConnection.setUI(new javax.swing.plaf.basic.BasicButtonUI());
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTestConnection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    private void loadSettings() {
        // Preferir db_settings.json
        java.nio.file.Path dbJsonPath = java.nio.file.Paths.get("db_settings.json");
        if (java.nio.file.Files.exists(dbJsonPath)) {
            try {
                String json = new String(java.nio.file.Files.readAllBytes(dbJsonPath), java.nio.charset.StandardCharsets.UTF_8);
                txtHost.setText(getJsonValue(json, "db.host", "localhost"));
                txtPort.setText(getJsonValue(json, "db.port", "3306"));
                txtDatabase.setText(getJsonValue(json, "db.database", ""));
                txtUsername.setText(getJsonValue(json, "db.username", "root"));
                txtPassword.setText(getJsonValue(json, "db.password", ""));
            } catch (java.io.IOException ioe) {
                logger.log(java.util.logging.Level.WARNING, "No se pudo leer db_settings.json", ioe);
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error al leer db_settings.json: " + ioe.getMessage(),
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                setDefaults();
            }
    } else {
        // JSON-only policy: if db_settings.json no existe, usar valores por defecto y notificar
        setDefaults();
        javax.swing.JOptionPane.showMessageDialog(this,
            "No se encontró 'db_settings.json'. Se usarán valores por defecto. Para persistir, guarde la configuración.",
            "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

        // Cargar textmebot_api.json si existe
        try {
            java.nio.file.Path jsonPath = java.nio.file.Paths.get("textmebot_api.json");
            if (java.nio.file.Files.exists(jsonPath)) {
                String json = new String(java.nio.file.Files.readAllBytes(jsonPath), java.nio.charset.StandardCharsets.UTF_8);
                java.util.regex.Matcher m = java.util.regex.Pattern.compile("\"textmebot_api\"\\s*:\\s*\"([^\"]*)\"").matcher(json);
                if (m.find()) txtApiTextmebot.setText(m.group(1));
            }
        } catch (java.io.IOException ioe) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo leer textmebot_api.json", ioe);
        }
    }

    private void setDefaults() {
        txtHost.setText("localhost");
        txtPort.setText("3306");
        txtDatabase.setText("");
        txtUsername.setText("root");
        txtPassword.setText("");
    }

    private String getJsonValue(String json, String key, String defaultValue) {
        if (json == null) return defaultValue;
        String pattern = "\\\"" + java.util.regex.Pattern.quote(key) + "\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"";
        java.util.regex.Matcher m = java.util.regex.Pattern.compile(pattern).matcher(json);
        if (m.find()) return m.group(1);
        return defaultValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHost = new javax.swing.JTextField();
        lblHost = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        lblDB = new javax.swing.JLabel();
        txtDatabase = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUsername1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblTitulo = new javax.swing.JLabel();
        btnTestConnection = new javax.swing.JButton();
        btnSaveSettings = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblApiTextmebot = new javax.swing.JLabel();
        txtApiTextmebot = new javax.swing.JTextField();
        CheckBoxAutoUpdater = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONFIGURACIÓN BASE DE DATOS");

        txtHost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblHost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHost.setText("HOST:");

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPort.setText("PORT:");

        txtPort.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDB.setText("DATABASE:");

        txtDatabase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("USERNAME:");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername1.setText("PASSWORD:");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("DATABASE SETTINGS");

        btnTestConnection.setBackground(new java.awt.Color(21, 134, 255));
        btnTestConnection.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnTestConnection.setForeground(new java.awt.Color(255, 255, 255));
        btnTestConnection.setText("Test Connection");
        btnTestConnection.setOpaque(true);
        btnTestConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestConnectionActionPerformed(evt);
            }
        });

        btnSaveSettings.setBackground(new java.awt.Color(21, 134, 255));
        btnSaveSettings.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSaveSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveSettings.setText("Guardar");
        btnSaveSettings.setOpaque(true);
        btnSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSettingsActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(21, 134, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setOpaque(true);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblApiTextmebot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApiTextmebot.setText("TEXTMEBOT API:");

        txtApiTextmebot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CheckBoxAutoUpdater.setBackground(new java.awt.Color(255, 255, 255));
        CheckBoxAutoUpdater.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckBoxAutoUpdater.setText("ACTUALIZAR DE FORMA AUTOMATICA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDB)
                            .addComponent(lblUsername)
                            .addComponent(lblUsername1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPort)
                                .addComponent(lblHost)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDatabase, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHost, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPassword)
                                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApiTextmebot, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnTestConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApiTextmebot)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxAutoUpdater))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername1)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnTestConnection)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApiTextmebot)
                    .addComponent(txtApiTextmebot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(CheckBoxAutoUpdater)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveSettings)
                    .addComponent(btnRegresar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestConnectionActionPerformed

        String host = txtHost.getText();
        String port = txtPort.getText();
        String database = txtDatabase.getText();
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());

        String url = "jdbc:mariadb://" + host + ":" + port + "/" + database;

        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(url, username, password)) {
            // use the connection to avoid "variable not used" and to verify connectivity
            try {
                if (conn != null && conn.isValid(2)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Conexión Exitosa!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Conexión Fallida: conexión no válida", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (java.sql.SQLException innerEx) {
                javax.swing.JOptionPane.showMessageDialog(this, "Conexión Fallida: " + innerEx.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Conexión Fallida: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTestConnectionActionPerformed

    private void btnSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSettingsActionPerformed

        // Collect fields
        String host = txtHost.getText();
        String port = txtPort.getText();
        String database = txtDatabase.getText();
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());

    // Persist settings to JSON only (db_settings.json)
    java.nio.file.Path dbJsonPath = java.nio.file.Paths.get("db_settings.json");
    // Escape values for JSON
    java.util.function.UnaryOperator<String> esc = s -> s == null ? "" : s.replace("\\", "\\\\").replace("\"", "\\\"");
    String json = "{"
        + "\"db.host\":\"" + esc.apply(host) + "\"," 
        + "\"db.port\":\"" + esc.apply(port) + "\"," 
        + "\"db.database\":\"" + esc.apply(database) + "\"," 
        + "\"db.username\":\"" + esc.apply(username) + "\"," 
        + "\"db.password\":\"" + esc.apply(password) + "\""
        + "}";
    try (java.io.FileWriter fw = new java.io.FileWriter(dbJsonPath.toFile(), false)) {
        fw.write(json);
    } catch (java.io.IOException ioex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al guardar configuración: " + ioex.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

        // If API key field has text, save/update textmebot_api.json (same format as attached file)
        String apiKey = txtApiTextmebot.getText() != null ? txtApiTextmebot.getText().trim() : "";
        if (!apiKey.isEmpty()) {
            java.nio.file.Path jsonPath = java.nio.file.Paths.get("textmebot_api.json");
            // escape backslashes and quotes in the value
            String escaped = apiKey.replace("\\", "\\\\").replace("\"", "\\\"");
            String jsonContent = "{\"textmebot_api\":\"" + escaped + "\"}";
            try (java.io.FileWriter fw = new java.io.FileWriter(jsonPath.toFile(), false)) {
                fw.write(jsonContent);
            } catch (java.io.IOException jex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Failed to save API file: " + jex.getMessage(),
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                // continue; do not abort DB connection test because of JSON write failure
            }
        }

        // Save updater.properties with auto_update preference
        try {
            java.nio.file.Path upPath = java.nio.file.Paths.get("updater.properties");
            java.util.Properties props = new java.util.Properties();
            props.setProperty("auto_update", Boolean.toString(CheckBoxAutoUpdater != null && CheckBoxAutoUpdater.isSelected()));
            try (java.io.FileOutputStream fos = new java.io.FileOutputStream(upPath.toFile())) {
                props.store(fos, "Updater settings");
            }
        } catch (Exception ex) {
            // Non-fatal
            logger.log(java.util.logging.Level.WARNING, "Could not save updater.properties", ex);
        }

        // Test the connection with saved values
        String url = "jdbc:mariadb://" + host + ":" + port + "/" + database;
        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(url, username, password)) {
            try {
                if (conn != null && conn.isValid(2)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Configuración guardada y conexión exitosa!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Conexión fallida: conexión no válida", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (java.sql.SQLException innerEx) {
                javax.swing.JOptionPane.showMessageDialog(this, "Conexión Fallida: " + innerEx.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Conexión Fallida: " + ex.getMessage(),
                    "Error de base de datos", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveSettingsActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        this.setVisible(false); // Hide frmDB
        frmLogin loginForm = new frmLogin(); // Create an instance of frmLogin
        loginForm.setVisible(true); // Show frmLogin
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmDB().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxAutoUpdater;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSaveSettings;
    private javax.swing.JButton btnTestConnection;
    private javax.swing.JLabel lblApiTextmebot;
    private javax.swing.JLabel lblDB;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JTextField txtApiTextmebot;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtHost;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
