/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author omarv
 */
public class frmMain extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMain.class.getName());

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximize the window
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Forms/icon.png")).getImage());
        // Set cursor to pointer for menus
        menuRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuOpcionesAvanzadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Set cursor to pointer for submenu items
        menuRegistrarComprobante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConsultarTodosComprobantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConsultarComprobantesNoCancelados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConsultarComprobantesCancelados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConsultarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAvanzadoEstadoComprobantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAvanzadoEstadoRopa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAvanzadoLocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAvanzadoMetodosPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAvanzadoRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAvanzadoServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAvanzadoUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReportesFinancieros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReportesCargaTrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReportesExportarComprobantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReportesHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Custom action for menu Salir
        menuSalir.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // TODO
            }

            @Override
            public void mousePressed(MouseEvent e) {
                // Set button text to Spanish
                UIManager.put("OptionPane.yesButtonText", "Sí");
                UIManager.put("OptionPane.noButtonText", "No");

                int response = javax.swing.JOptionPane.showConfirmDialog(
                        null,
                        "¿Estás seguro de salir?",
                        "SISTEMA DE LAVANDERÍA 1.0",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );

                if (response == javax.swing.JOptionPane.YES_OPTION) {
                    System.exit(0); // Exit the application
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                // TODO
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                // TODO
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // TODO
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        menuRegistrarComprobante = new javax.swing.JMenuItem();
        menuRegistrarCliente = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();
        menuConsultarTodosComprobantes = new javax.swing.JMenuItem();
        menuConsultarComprobantesNoCancelados = new javax.swing.JMenuItem();
        menuConsultarComprobantesCancelados = new javax.swing.JMenuItem();
        menuConsultarClientes = new javax.swing.JMenuItem();
        menuOpcionesAvanzadas = new javax.swing.JMenu();
        menuAvanzadoEstadoComprobantes = new javax.swing.JMenuItem();
        menuAvanzadoEstadoRopa = new javax.swing.JMenuItem();
        menuAvanzadoLocales = new javax.swing.JMenuItem();
        menuAvanzadoMetodosPago = new javax.swing.JMenuItem();
        menuAvanzadoRoles = new javax.swing.JMenuItem();
        menuAvanzadoServicios = new javax.swing.JMenuItem();
        menuAvanzadoUsuarios = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReportesFinancieros = new javax.swing.JMenuItem();
        menuReportesCargaTrabajo = new javax.swing.JMenuItem();
        menuReportesExportarComprobantes = new javax.swing.JMenuItem();
        menuReportesHistorico = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE LAVANDERIA 1.0");

        desktopPane.setBackground(new java.awt.Color(171, 171, 171));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        menuRegistrar.setText("Registrar");
        menuRegistrar.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuRegistrarComprobante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuRegistrarComprobante.setText("Comprobante");
        menuRegistrarComprobante.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuRegistrarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarComprobanteActionPerformed(evt);
            }
        });
        menuRegistrar.add(menuRegistrarComprobante);

        menuRegistrarCliente.setText("Cliente");
        menuRegistrarCliente.setMargin(new java.awt.Insets(3, 5, 4, 6));
        menuRegistrar.add(menuRegistrarCliente);

        jMenuBar1.add(menuRegistrar);

        menuConsultar.setText("Consultar");
        menuConsultar.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuConsultarTodosComprobantes.setText("Todos los Comprobantes");
        menuConsultarTodosComprobantes.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuConsultar.add(menuConsultarTodosComprobantes);

        menuConsultarComprobantesNoCancelados.setText("Comprobantes NO Cancelados");
        menuConsultarComprobantesNoCancelados.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuConsultar.add(menuConsultarComprobantesNoCancelados);

        menuConsultarComprobantesCancelados.setText("Comprobantes YA Cancelados");
        menuConsultarComprobantesCancelados.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuConsultar.add(menuConsultarComprobantesCancelados);

        menuConsultarClientes.setText("Clientes");
        menuConsultarClientes.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuConsultar.add(menuConsultarClientes);

        jMenuBar1.add(menuConsultar);

        menuOpcionesAvanzadas.setText("Opciones Avanzadas");
        menuOpcionesAvanzadas.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuAvanzadoEstadoComprobantes.setText("Estado Comprobantes");
        menuAvanzadoEstadoComprobantes.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuOpcionesAvanzadas.add(menuAvanzadoEstadoComprobantes);

        menuAvanzadoEstadoRopa.setText("Estado Ropa");
        menuAvanzadoEstadoRopa.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuOpcionesAvanzadas.add(menuAvanzadoEstadoRopa);

        menuAvanzadoLocales.setText("Locales");
        menuAvanzadoLocales.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuOpcionesAvanzadas.add(menuAvanzadoLocales);

        menuAvanzadoMetodosPago.setText("Métodos de Pago");
        menuAvanzadoMetodosPago.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuOpcionesAvanzadas.add(menuAvanzadoMetodosPago);

        menuAvanzadoRoles.setText("Roles");
        menuAvanzadoRoles.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuOpcionesAvanzadas.add(menuAvanzadoRoles);

        menuAvanzadoServicios.setText("Servicios");
        menuAvanzadoServicios.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuOpcionesAvanzadas.add(menuAvanzadoServicios);

        menuAvanzadoUsuarios.setText("Usuarios");
        menuAvanzadoUsuarios.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuOpcionesAvanzadas.add(menuAvanzadoUsuarios);

        jMenuBar1.add(menuOpcionesAvanzadas);

        menuReportes.setText("Reportes");
        menuReportes.setMargin(new java.awt.Insets(3, 8, 3, 8));

        menuReportesFinancieros.setText("Financieros");
        menuReportesFinancieros.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuReportes.add(menuReportesFinancieros);

        menuReportesCargaTrabajo.setText("Carga de trabajo");
        menuReportesCargaTrabajo.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuReportes.add(menuReportesCargaTrabajo);

        menuReportesExportarComprobantes.setText("Exportar todos los comprobantes");
        menuReportesExportarComprobantes.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuReportes.add(menuReportesExportarComprobantes);

        menuReportesHistorico.setText("Historico comprobantes");
        menuReportesHistorico.setMargin(new java.awt.Insets(3, 6, 4, 6));
        menuReportes.add(menuReportesHistorico);

        jMenuBar1.add(menuReportes);

        menuSalir.setText("Salir");
        menuSalir.setMargin(new java.awt.Insets(3, 8, 3, 8));
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistrarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarComprobanteActionPerformed
        // TODO add your handling code here:
        // Check if the internal frame is already open
        for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof frmRegistrarComprobante) {
                frame.toFront(); // Bring the existing frame to the front
                try {
                    frame.setSelected(true); // Select the frame
                } catch (java.beans.PropertyVetoException ex) {
                    ex.printStackTrace();
                }
                return; // Exit the method to prevent opening a new instance
            }
        }

        // Create a new instance of frmRegistrarComprobante
        frmRegistrarComprobante registrarForm = new frmRegistrarComprobante();

        // Add the internal frame to the desktop pane
        desktopPane.add(registrarForm);

        // Make the internal frame visible
        registrarForm.setVisible(true);
    }//GEN-LAST:event_menuRegistrarComprobanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAvanzadoEstadoComprobantes;
    private javax.swing.JMenuItem menuAvanzadoEstadoRopa;
    private javax.swing.JMenuItem menuAvanzadoLocales;
    private javax.swing.JMenuItem menuAvanzadoMetodosPago;
    private javax.swing.JMenuItem menuAvanzadoRoles;
    private javax.swing.JMenuItem menuAvanzadoServicios;
    private javax.swing.JMenuItem menuAvanzadoUsuarios;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenuItem menuConsultarClientes;
    private javax.swing.JMenuItem menuConsultarComprobantesCancelados;
    private javax.swing.JMenuItem menuConsultarComprobantesNoCancelados;
    private javax.swing.JMenuItem menuConsultarTodosComprobantes;
    private javax.swing.JMenu menuOpcionesAvanzadas;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JMenuItem menuRegistrarCliente;
    private javax.swing.JMenuItem menuRegistrarComprobante;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuReportesCargaTrabajo;
    private javax.swing.JMenuItem menuReportesExportarComprobantes;
    private javax.swing.JMenuItem menuReportesFinancieros;
    private javax.swing.JMenuItem menuReportesHistorico;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
